// The worked example shown on /example, generated by scripts/build_example_analysis.py
// from a real multi-day CGM export. De-identified at generation time.

export type ExampleProbe = {
  key: string;
  task: string;
  cohort: string;
  score: number;
  percentile: number | null;
  roc_auc: number;
  n_subjects: number;
  /** Every 5th percentile of this probe's score across the corpus sample. */
  corpus_deciles: number[] | null;
};

export type ExampleDay = {
  label: string;
  weekday: string;
  coverage: number;
  values_mg_dl: (number | null)[];
  mask: number[];
  state: number[];
  event: number[];
  embedding: number[];
  clinical: {
    n_observed: number;
    mean_mg_dl: number;
    sd_mg_dl: number;
    coefficient_of_variation: number;
    gmi_percent: number;
    time_below_70: number;
    time_in_range_70_180: number;
    time_above_180: number;
    min_mg_dl: number;
    max_mg_dl: number;
  } | null;
  probes: ExampleProbe[];
};

export type ExampleAnalysis = {
  note: string;
  source: string;
  n_days: number;
  heads_shipped: number;
  heads_with_signal: number;
  signal_floor: number;
  heads_below_floor: { key: string; task: string; cohort: string; roc_auc: number }[];
  days: ExampleDay[];
  similarity: number[][];
  reference_windows: number;
};

/** Plain-English names for the probe tasks, which are stored as bare keys. */
export const TASK_LABEL: Record<string, string> = {
  glucotype: "Glucose variability subtype",
  insulin_resistance: "Insulin resistance",
  diabetes_risk: "Diabetes risk",
  beta_cell_dysfunction: "Reduced insulin production",
  obesity: "Body-mass category",
  hyperlipidemia: "High blood lipids",
  hypoglycemia: "Low-glucose episodes",
  hba1c_band: "HbA1c band",
};

export function taskLabel(task: string): string {
  const bare = task.includes(":") ? task.split(":").slice(1).join(":") : task;
  return TASK_LABEL[bare] ?? bare.replaceAll("_", " ");
}

export const COHORT_LABEL: Record<string, string> = {
  hall: "Hall",
  stanford: "Stanford",
  cgmacros: "CGMacros",
  shanghai_t2dm: "Shanghai T2DM",
};

export function cohortLabel(c: string): string {
  return COHORT_LABEL[c] ?? c.replaceAll("_", " ");
}


// ---------------------------------------------------------------------------------------
// Readings derived from the data rather than written next to it.
//
// The page used to name specific weekdays in its prose. Regenerating the example from a
// different recording, or fixing the day boundaries as happened once already, silently turned
// that prose into fiction. These helpers compute what the page asserts.

export type WeekReading = {
  mostAlike: { a: ExampleDay; b: ExampleDay; similarity: number } | null;
  leastTypical: ExampleDay | null;
  typicality: { day: ExampleDay; mean: number }[];
  complete: ExampleDay[];
  sparse: ExampleDay[];
  peakSpread: { low: ExampleDay; high: ExampleDay } | null;
};

export function readWeek(data: ExampleAnalysis): WeekReading {
  const { days, similarity } = data;

  const typicality = days
    .map((day, i) => {
      const others = similarity[i]!.filter((_, j) => j !== i);
      return { day, mean: others.reduce((a, b) => a + b, 0) / (others.length || 1) };
    })
    .sort((a, b) => b.mean - a.mean);

  const complete = days.filter((d) => d.coverage >= 0.9);
  const sparse = days.filter((d) => d.coverage < 0.9);

  let mostAlike: WeekReading["mostAlike"] = null;
  for (let i = 0; i < days.length; i += 1) {
    for (let j = i + 1; j < days.length; j += 1) {
      const s = similarity[i]![j]!;
      if (!mostAlike || s > mostAlike.similarity) {
        mostAlike = { a: days[i]!, b: days[j]!, similarity: s };
      }
    }
  }

  // Among complete days only: a sparse day is unlike the others because of its gaps, which
  // is a different and less interesting statement.
  const completeTypicality = typicality.filter((t) => t.day.coverage >= 0.9);
  const leastTypical = completeTypicality.length
    ? completeTypicality[completeTypicality.length - 1]!.day
    : null;

  const withPeaks = complete.filter((d) => d.clinical);
  const peakSpread = withPeaks.length >= 2
    ? {
        low: withPeaks.reduce((a, b) => (a.clinical!.max_mg_dl <= b.clinical!.max_mg_dl ? a : b)),
        high: withPeaks.reduce((a, b) => (a.clinical!.max_mg_dl >= b.clinical!.max_mg_dl ? a : b)),
      }
    : null;

  return { mostAlike, leastTypical, typicality, complete, sparse, peakSpread };
}

/** "Wednesday" from a day, or its label if the weekday is missing. */
export function dayName(d: ExampleDay): string {
  return d.weekday || d.label;
}


/** English ordinal suffix. The page was rendering "22th" and "91th". */
export function ordinal(n: number): string {
  const v = Math.round(n);
  const mod100 = v % 100;
  if (mod100 >= 11 && mod100 <= 13) return `${v}th`;
  return `${v}${["th", "st", "nd", "rd"][v % 10] ?? "th"}`;
}
